### ISSUE TITLE
support rxjs-7.x ?

### ISSUE THREAD

**Issue by transtone** [Raiondesu/vusx#7]
rxjs-7.x is out, can vuse-rx support it ?

**Comment by Raiondesu** [comment]
Thank you for creating this!\
I think rxjs 7 doesn't bring that many incompatible changes, so yes, it should work.

I'll test this out, however. And if there are any breaks, I'll post an update here.

**Comment by Raiondesu** [comment]
Tested with rxjs 7.1.0, it works fine.

But I'll update the lib nonetheless, just to be sure. :)
