### ISSUE TITLE
Docs return 404 when you hit the Get Started button

### ISSUE THREAD

**Issue by NinjaTycoon** [Raiondesu/vusx#9]
true of Stable and Beta docs.

**Comment by Raiondesu** [comment]
Hi, thanks for the report!
I cannot reproduce this, however. Can you, please, tell more about your environment (browser, OS)?

**Comment by Raiondesu** [comment]
Hey, @NinjaTycoon, I'm closing this as stale, hope you don't mind. Please, let me know if the issue actually is replicable.
